"""This module perform granger test on timeseries."""

# topic timeseries is generated by
# date => sum_of_theta
# apply stationary
# get rid of dates (Yes)

# nontext time series
# date => value
# apply stationary
# get rid of dates (Yes)

## make time series stationary by
# To make the
# input series stationary, we smooth with a moving average filter with
# window size 3 (average with adjacent values) and use first differ-
# ences (x t ) − (x t−1 ) of each series. We test causality with up to 5
# day lags and pick the lag which shows highest significance.

# do it for both time series


# run granger test and chose p-value, 0.05 (typically ≤ 0.05) significant

# would you run pearson coefficents, I would say yes
# use granger test for pearson coefficients

# The coefficients of lagged x terms estimate
# the impact of x to y.
# P p
# i=1 b i
# We average the x term coefficients, |p| , as an impact value.


# To list coefficients use gc_res[3][1][1].params
# the first p coefficents are for y
# the second p coefficents are for x
# the last is intercept.